name: lead_profiler
channels:
  - defaults
dependencies:
  - python=3.10
  - pip:
      - black==23.12.1
      - anthropic
      - googlenews==1.6.12
      - lxml==5.1.0
      - pytest
      - requests
      - setuptools==69.0.3
      - typing_extensions==4.9.0
      - streamlit
      - wikipedia==1.4.0
